nanovms/ops

lepton/image.go

Write to mkfs stdin in goroutine otherwise WriteString() blocks if manifest is bigger than pipe buffer (64K on Linux).

Write to mkfs stdin in goroutine otherwise WriteString() blocks

---

lepton/elf.go
ops.go

- printManifestHandler: Do not crash on "file does not exist"
- getSharedLibs: Better error reporting

printManifestHandler: Do not crash on "file does not exist"

---

ops.go

Low hanging fruit. Don't do download and all of that stuff before checking for a supported hypervisor.
It doesn't seem worth it to DRY those two blocks of code until they do a bit more. Also, I am sure there is a plan for uniform error handling, so I don't want to just the gun and extract out the common error to something more DRY yet.

Do hypervisor check first.

---

lepton/qemu.go
lepton/qemu_test.go

This is a refactor. The idea is to make it easy to simply transform a `RunConfig` into a "Qemu" struct (or just to take a `RunConfig` and convert it into qemu command line string). The next step is to get the correct parameters onto the cli and into the `RunConfig` to complete issues https://github.com/nanovms/ops/issues/173 and https://github.com/nanovms/ops/issues/177.
I have unit test and I have successfully run the commands with the various options but if you agree with this commit please eye the rendering functions to ensure I did not miss anything that will break the rendering of a qemu command.

Refactor Qemu code for easy tranformation from run configuration.

---

lepton/qemu.go

For #125
After change nanovms/nanos#480, there is no need to map the same image twice to qemu. Removed "ide" mapping, as it's not used anymore bo boot.

Removed ide drive mapping as it's not neeed after nanovms/nanos#480

---

lepton/const.go

Right now we seg fault, if there is a local build use it.

make ops works even if we cant lookup the latest version

---

install.sh
lepton/hv_support_darwin.go
lepton/hv_support_linux.go
lepton/qemu.go
lepton/qemu_test.go

Here we implement a virtualization hardware support check by making the system call on `Darwin` and by reading `/proc/cpuinfo` on `Linux`. We use this to know if we should add an `-accel` option to qemu. In neither case do we shell. 
However with this I have noticed that, while ` qemu  -accel-hvf ` works fine on `macos`; when using `-accel kvm` on `linux` qemu hangs when running an ops image. I've tested this with a `helloworld.go` image on my `AMD Ryzen` host. I'll certainly test  some more on other machine archs and distributions. 
TODO:

Add accel hvf flag

---

ops.go

`Ops run -x <elf>`
`Ops load --accel <package> ...`
There is a little bit of an opportunity to refactor the `load` and `run` flags -> config stuff of course.

Add accel(x) flag for cpu virt ext. support.

---

lepton/qemu_test.go

Not sure why this test is required. May be it should be removed altogether.

Do not run TestGroupPermission on macOS

---

lepton/image.go

- check for ~/.ops/common existence was broken (so the function did not do anything)
- fix download and extract

Fix addDefaultFiles()

---

lepton/image.go

This magically fixes running with acceleration enabled (ops run -x).

Add USER environment variable by default.

---

ops.go

i don't see a use for staging but this will prevent weird perm errors when nuking it

fixing perms for staging

---

lepton/ldd_darwin.go

- Fix LD_LIBRARY_PATH/DT_RPATH/DT_RUNPATH precedence. From man 8 ld-linux.so:
If a shared object dependency does not contain a slash, then it is searched
for in the following order:
o  Using the directories specified in the DT_RPATH dynamic section attribute
of the binary if present and DT_RUNPATH attribute does not exist.
Use of DT_RPATH is deprecated.
o  Using the environment variable LD_LIBRARY_PATH (unless the executable is
being run in secure-execution mode; see below in which case it is ignored).
o  Using the directories specified in the DT_RUNPATH dynamic section attribute
of the binary if present.
- LD_LIBRARY_PATH, DT_RPATH, DT_RUNPATH can contain multiple entries separated by ':'
- Implement $ORIGIN token expansion for DT_RPATH and DT_RUNPATH

Implement $ORIGIN expansion for DT_RPATH and DT_RUNPATH

---

lepton/manifest.go

mkfs tuple parser does not skip whitespace characters properly when the tuple is empty

---

lepton/image.go
lepton/manifest.go

- handle errors from AddDirectory and addMappedFiles
- ignore invalid symlinks

Error handling when generating the manifest

---

cmd/image.go
cmd/load.go
cmd/utils.go
lepton/gcp.go
lepton/image.go
lepton/onprem.go
lepton/provider.go

Building with package
`~/go/src/github.com/nanovms/ops/ops image create -c config.json -p node_v11.5.0 -a ex.js`  
Building without package
`~/go/src/github.com/nanovms/ops/ops image create -c config.json -a hello`

Issue #309: Building GCP image with package

---

lepton/ldd_linux.go
lepton/ldd_test.go

Calling os.Chmod will fail if the current user doesn't have write permission
for a given file, but can still run ldd (e.g., /bin/ls). This patch just
leaves the permissions alone and lets ldd fail if there's no execution
rights.
I see the chmod was added in 3a3ba2307b24aa15ed50d38d4800f5e9cd2ea76b but I can't figure out what path expects execute permissions to not be set. If a binary doesn't have +x set, it seems safer to have the user choose to grant the permission after seeing an error instead of automatically clobbering the mode with 755.
/cc @tijoytom

Don't chmod in linux getSharedLibs

---

lepton/image.go
lepton/manifest.go
lepton/manifest_test.go

Currently, we ignore scenarios where we dont find required files while
building image. Catching errors for such scenarios explicitly and
putting out.

Catch missing file scenarios in image generation

---

lepton/image.go
lepton/ldd_darwin.go
lepton/manifest.go
lepton/manifest_test.go

Some files are added from $NANOS_TARGET_ROOT so check their existence also there.
AddDirectory() should also probably be fixed in this way but it never
was able to lookup in target root.

Fix nanos go tests on macOS

---

lepton/const.go
lepton/image.go

"mkfs -b" writes proper MBR which is required by some cloud providers (AWS).

Use "mkfs -b" to build the final image.

---

cmd/run.go
lepton/config.go
lepton/qemu.go

Added support for enabling qemu's GDB interface. Only debugging over TCP
is supported (fortunately, it's the most common option, and the most
useful for us), and the user can specify the TCP port to be used for the
gdb interface. Specifying a port also enables the gdb interface --
specifying one without the other would be meaningless, since only TCP is
supported.
Signed-off-by: Alexandru Lazar <alazar@startmail.com>

Add gdb enable and port flag to ops run

---

.circleci/config.yml
install.sh

Use a homebrew formula that we can vector towards a known working version of qemu. At the time, this means 4.2.0-rc0, which contains a critical fix for a bug in TCG that was causing crashes with node.js when not running in accel (-x) mode.
See https://github.com/nodejs/node/issues/19348 and #403 
resolves #414

macos install: use a homebrew formula for qemu 4.2.0-rc0

---

README.md

Add missing closing brace and replace duplicate link to the badge image
to report link.

README.md: Fix goreport badge

---

lepton/image.go
lepton/package.go

These changes resolve #250 .
I have introduced a new parameter `showProgress` to the function `DownloadFile`. This allows the calling code to determine whether a progress spinner should print in the terminal for this download. I have added a useful helper function `DownloadFileWithProgress`, which conforms to the previous function signature, but sets `showProgress` to `true` automatically.
The instance where the package list should not display a spinner sets this explicitly to `false`. I can write a wrapper for this case too, but since this is the only occurrence it did not seem strictly essential at this stage. Let me know whether you would like me to add `DownloadFileWithoutProgress` as part of these changes too @eyberg ?

Disable spinner for pkg list

---

lepton/config.go

For consistency with NewConfig(), RuntimeConfig() should also return a configuration with hardware acceleration enabled.

RuntimeConfig(): enable hardware acceleration by default

---

lepton/volume.go

Fixes: #611 
I replaced tab-fmt.Print style with tablewriter in volume `GetAll`.

Use tablewriter as volume list (#611)

---

cmd/volume.go
lepton/volume.go

Prints the volume size alongside other values in the list volumes table. It first parses the size value into a human readable format using the helper functions in `lepton/helpers.go`.
Example
```bash
./ops volume list
+----------+--------------------------------------+--------+------------------------------------------------+
|   NAME   |                 UUID                 |  SIZE  |                      PATH                      |
+----------+--------------------------------------+--------+------------------------------------------------+
| test_vol | 9aa1a2a1-4d6d-a340-03d2-a77b05484c16 | 1.0 kB | /home/ahmedaabouzied/.ops/volumes/test_vol.raw |
+----------+--------------------------------------+--------+------------------------------------------------+
```
If there is an error …

Print volume size in volume list table

---

cmd/image.go
lepton/aws.go
lepton/azure.go
lepton/digital_ocean.go
lepton/gcp.go
lepton/onprem.go
lepton/openstack.go
lepton/provider.go
lepton/vsphere.go
lepton/vultr.go

resolves #502 
`ops image sync <image_name> -t <cloud_provider>` allows user to transfer locally existing image to target cloud provider
since original `ops image` does not accept flags for some provider-related configs, user will need to set said fields in config

add image sync command

---

cmd/instance.go
lepton/aws.go
lepton/utils.go

In PR I fixed following problems.
1. CLI wasn't picking up zone as given condition was checking for null value.
2. Added fix for 389 issue now it just shows invalid zone doesn't print complete stack trace. To fix this issue I created separate util.go file for lepton package and added exitWithError function.
3. Previously code was picking up first VPC from multiple VPCs to create SG which is wrong as while creating instance AWS SDK uses default VPC if you don't mention one. So I added code to retrieve default VPC from list. Current code works fine with new account as it contains only default VPC. In future, we should accept VPC from user if not given we can use default one I have added TODo for same in code.

Fixing 389 and other issues

---

cmd/run.go

Added support to accept manifest file through config file. Right now precedence is given to command line argument. If command line argument is not given manifest value will be populated via config file.

Adding support to accept manifest file name in config file

---

lepton/ldd_linux.go

The solution works for me. Please, tell me if we need anything more.
Raw image:
---
`emikhalev@ubuntu:~/go/github.com/emikhalev/ops$ file /home/emikhalev/go/github.com/emikhalev/ops/test.img
/home/emikhalev/go/github.com/emikhalev/ops/test.img: data`
`emikhalev@ubuntu:~/go/github.com/emikhalev/ops$ ./ops run ./test.img
Only ELF binaries are supported. Is thia a Linux binary? run 'file /home/emikhalev/go/github.com/emikhalev/ops/test.img' on it`
ELF file
---
`emikhalev@ubuntu:~/go/github.com/emikhalev/ops$ file /home/emikhalev/go/github.com/emikhalev/ops/test
/home/emikhalev/go/github.com/emikhalev/ops/test: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped`
`emikhalev@ubuntu:~/go/github.com/emikhalev/ops$ ./ops run ./test
booting …

ensure a valid ELF file provided (#698)

---

lepton/aws.go

Issue - #672
Fixed invalid region message for aws in "ops instance list"

Bugfix 672 - invalid region message

---

lepton/aws.go

For some reason an import takes >20 minutes for me.  In this case the error message is very confusing:
```
erik@carbon ~/tmp/nanovm/golang $ ops image create -t aws -c config.json -a hello --show-warnings
Successfully uploaded "hello-image" to "mackdanz-vmimport"
waiting for snapshot - can take like 5min.... 
import done - took 14.981148 minutes
MissingParameter: The request must contain the parameter resourceIdSet
status code: 400, request id: bc9cfbbf-5497-4aac-b545-ff0a177aac17
```
This change results in a more helpful message:
```
erik@carbon ~/tmp/nanovm/golang $ ops image create -t aws -c config.json -a hello --show-warnings
Successfully uploaded "hello-image" to "mackdanz-vmimport"
waiting for snapshot - can take like 5min.... 
import timed out after 14.970942 minutes …
```

Better messaging for image import timeout

---

lepton/aws.go

The AWS VM import times out after 15 minutes, but for some reason it requires >20 minutes for me.  Please increase the timeout.

Wait longer for AWS image import

---

cmd/instance.go
lepton/aws.go
lepton/azure.go
lepton/config.go
lepton/gcp.go
lepton/openstack.go

* Use command flag or configuration file to set instance name
* Use image name and timestamp to create instance name if not provided
* Update aws, azure, gcp and openstack instance name on creating them

Allow set instance name (closes #807)

---

cmd/package.go

An edge case was found in the previous pkg list sorting where uppercase package names would be sorted above lowercase package names, as found here:
```
$ go run ops.go pkg list
+--------------------+-----------+------------+------------+--------------------------------+
|    PACKAGENAME     |  VERSION  |  LANGUAGE  |  RUNTIME   |          DESCRIPTION           |
+--------------------+-----------+------------+------------+--------------------------------+
| R_3.4.4            | 3.4.4     | R          | R          | R                              |
+--------------------+-----------+------------+------------+--------------------------------+
| bind_9.13.4        | 9.13.4    | c          | bind9      | bind9 - dns resolver           | …
```

pkg list sorting now handles upper- and lowercase

---

cmd/run.go
cmd/utils.go
lepton/config.go
lepton/image.go
lepton/manifest.go

(closes #838)
Users can specify the static IP address using the next command format:
`ops run main -b -t tap0 --ip-address 192.168.42.20 --gateway 192.158.42.255 --netmask 255.255.0.0`
The network configuration parameters are added to the manifest file:
```
...
gateway:192.168.42.1
ipaddr:192.168.42.20
booted:
netmask:255.255.255.0
program:/ops-go-test/main
environment:(OPS_VERSION:NANOS_VERSION:0.1.30 USER:root PWD:/)
arguments:(0:../ops-go-test/main))
```

Add static IP address to manifest on run command (closes #838)

---

cmd/load.go
cmd/run.go

This PR adds a flag to ops to include a manifest symbol that activates an 'strace -c' like summary of syscalls at vm exit to the ops run and load commands.

Add support for syscall summary flag in load and run commands

---

cmd/run.go

Set empty default tap device name (closes #856)

---

lepton/ldd_linux.go

The presence of a dynamic section in an ELF file does not necessarily make the file dynamically linked: a file may have a dynamic section while not having an dependency on shared libraries. The ArangoDB server executable binary for Linux (/usr/sbin/arangod file in https://download.arangodb.com/arangodb37/Community/Linux/arangodb3_3.7.6-1_amd64.deb) is an example of such files.
When a statically linked executable is run with LD_TRACE_LOADED_OBJECTS=1 (as done in the getSharedLibs() method), the dynamic linker executes the binary instead of listing its shared libraries, and this makes getSharedLibs() fail; as a result, "ops run" does not work.
An ELF file is dynamically linked only if it has a dynamic section and this section contains at least one DT_NEEDED entry. The ImportedLibraries() …

ldd_linux: fix check for dynamically linked executable

---

lepton/aws.go

* Having aws env variables set (AWS_ACCESS_KEY and AWS_SECRET_ACCESS) overrides file credentials

load aws credentials from ~/.aws./credentials (closes #864)

---

cmd/image.go
cmd/utils.go
cmd/utils_test.go
lepton/aws.go
lepton/aws_image.go
lepton/cloud.go
lepton/digital_ocean_image.go
lepton/digital_ocean_test.go
lepton/gcp_image.go
lepton/onprem_image.go
lepton/openstack_image.go

* Allow to delete more than one image specified on command arguments
* Implement onprem get images method
* Separate concerns of presentation and image getting on onprem provider
* Fix name of aws images list
* Change image cloud "created at" field type

Allow to delete old image using a time notation (closes #473)

---

lepton/ldd_darwin.go

Fixes undefined reference compile error to ErrorColor

ErrorColor package reference missing in ldd_darwin

---

cmd/cmd_instance.go

* Remove projectid and zone flags from create instance handler as providerFlags is already reading them

read imagename flag on creating instance

---

fs/manifest.go
lepton/image.go

If `RADAR_KEY` env variable is present and `RADAR_IMAGE_NAME` isn't specified ops uses the image name to set the `RADAR_IMAGE_NAME` value.

Add radar image name env variable (closes #905)

---

cmd/cmd_image.go
lepton/image.go
lepton/openstack_image.go
lepton/openstack_instance.go
lepton/openstack_volume.go

(closes #912)
* Fix volumes name display in openstack
* Remove mandatory bucket from openstack cloud providers
* Fix display of IP addresses on listing ovh instances
* Delete image used to create volume in openstack

Fix image name used to create an image in openstack 

---

cmd/cmd_deploy.go
cmd/flags_create_instance.go
cmd/flags_create_instance_test.go
config/config.go
lepton/aws_image.go
lepton/aws_instance.go
lepton/aws_network.go
lepton/aws_volume.go
lepton/azure_instance.go
lepton/gcp_image.go
lepton/gcp_instance.go
lepton/gcp_network.go
lepton/onprem_instance.go
lepton/openstack_instance.go
lepton/provider.go
qemu/qemu_unix.go

closes #916 
* Once DomainName, SecurityGroup, Subnet, Tags and VPC are only used on cloud providers it makes more sense to have them on CloudConfig than in RunConfig.
* BaseName was deprecated in favor of the key InstanceName

Move keys from RunConfig to CloudConfig

---

cmd/cmd_image_test.go
cmd/cmd_pkg.go
cmd/flags_build_image.go
cmd/flags_build_image_test.go
cmd/flags_nightly.go
cmd/flags_pkg.go
cmd/utils_test.go
lepton/volume.go

Although the flag was setup in command we weren't using the flag value to change the volume size.
Also, pkg load command was setting 2 times the nanos tools paths in the configuration file.

Set onprem volume flag size

---

cmd/cmd_update.go

To use custom nanos build, user overwrites files in `~/.ops/0.1.xx` directory. To go back to stock install, if user then deletes `~/.ops/0.1.xx` directory and executes `ops update` command, it does not re-create that directory (unless `~/.ops/latest.txt` file is also deleted).
PR adds a check for directory existence.

Download nanos when version directory doesn't exist

---

cmd/flags_build_image.go

```sh
$ mkdir -p test/foo.bar/publish/
$ cp myApp test/foo.bar/publish/
$ ops build test/foo.bar/publish/myApp -t hyper-v
```
> Bootable image file:/home/am11/.ops/vhdx-images/foo.vhdx
> Bootable image file:/home/am11/.ops/vhdx-images/myApp.vhdx

Use basename for CloudConfig.ImageName

---

cmd/cmd_pkg.go
cmd/download_package.go
cmd/flags_pkg.go

* store package files in local_packages on using ops pkg get
* if package does not exist in ~/.ops/packages downloads it
* if local package does not exist displays error message
* Remove package tar file after extracting

use a local package when specified (closes #943)

---

cmd/flags_run_local_instance.go
cmd/flags_run_local_instance_test.go

if the same port is specified in the command flag and in the configuration file do not append duplicated port to configuration (closes #961)

De-duplicate ports 

---

cmd/flags_run_local_instance.go
cmd/flags_run_local_instance_test.go

Defaults are now set by nanos, so it works consistently across `ops run`, `ops instance create` and other similar commands.

Remove default gateway/netmask handling from ops

---

PACKAGES.md

References to environment variables should be under double quotes, and the SHA checksum needs to be calculated on the tar.gz file instead of the uncompressed package folder.

Package docs: fix environment variables and shasum command line

---

cmd/cmd_image.go
cmd/provider.go
provider/provider.go

External libraries can use the cloud provider factory to easily get a specific cloud provider.

Expose cloud provider factory

---

cmd/flags_build_image.go
cmd/flags_build_image_test.go
cmd/flags_run_local_instance.go
cmd/flags_run_local_instance_test.go
fs/manifest.go
lepton/image.go
types/config.go

The network addresses flags are now handled along with build image flags because they affect the images manifest file. Until now static addresses were only supported when we wanted to launch an instance locally (for example, in run command). After this change, ops is able to upload images with static addresses to cloud providers.

support static ipv6 (closes #1055)

---

fs/manifest.go

This adds a config.json option ntpResetThreshold specifying the threshold of the number of seconds of time difference
before ntp resets the time directly instead of slewing.

Add config option for ntp_reset_threshold

---

fs/manifest.go
lepton/image.go
types/config.go

This adds a new section for config.json, "ManifestPassthrough", that takes the key/value pairs from that section
and inserts them directly into the manifest without validation or processing. Intended to be undocumented
for use with debugging or bleeding edge nanos options.

Add ability to pass options from json directly to manifest

---

lepton/image.go

* If a port is defined in the configuration or in the flag, the env var "OPS_PORT" with the port value is added to nanos image

Add port env var (closes #1014)

---

aws/aws_instance.go
aws/aws_network.go

(closes #1017)
* Enable AWS to assign an ipv6 IP to instance nic
* Allow creating a VPC and a Subnet with a specified name
* Set ipv6 CIDR block on the subnet from the VPC ipv6 CIDR range
* Move subnet creation to a dedicated method

Add aws firewall rules to allow ipv6 traffic

---

qemu/qemu_unix.go

In the workaround to allow building images for aarch64 / virt platform, default to using GICv2 and locating kernel.img in the current working directory.

aarch64: default to gic v2 and kernel.img in CWD

---

cmd/cmd_pkg.go
lepton/ldd.go
lepton/ldd_darwin.go
lepton/ldd_linux.go

1. Added ELF validation to package load command
2. Added `isELF` function placeholder to `darwin`.
3. Refactored ELF validation codes in `getSharedLibs` as separated function.

Validate ELF upon package loading

---

cmd/cmd_pkg.go
cmd/cmd_root.go
cmd/flags_run_local_instance.go
cmd/flags_run_local_instance_unix.go
util/slice/string.go
util/slice/string_test.go

Fixed port conflict error message to be human-readable

Fix Port Conflict Error

---

cmd/cmd_pkg.go
cmd/download_package.go
upcloud/upcloud.go

Added checking for existing package first before deciding to download it.

Prevent 'pkg describe' to redownload existing package

---

cmd/flags_run_local_instance.go

This adds a flag that is passed to nanos that prints a list of filenames
the application tried to open but were not found. The intended use is to
easily discover dynamic libraries that need to be in the image but are not
included by ops.

Add missing files report flag

---

lepton/package.go

With this change, Ops can load packages containing symbolic links.

Packages: add support for symlinks

---

lepton/const.go

The broken test isn't related to the code changes. The `local_packages` directory doesn't exist at the moment that the test is running in circleci.

create local packages directory if it does not exist in flags pkg tests

---

cmd/cmd_image.go
cmd/cmd_root.go

```
arknable@arknable-x1c:~/.../ops$ go run ops.go run $HOME/Development/Project/nanovms/example/hello/hello c ../example/issue_441/config.json --show-errors
Error: invalid argument or flag provided, use --help for usage information. Probably what you mean was '-c' instead of 'c'?
Usage:
ops run [elf] [flags]
Flags:
..........
```

Check if one or more argument failed to be set

---

cmd/flags_pkg.go
types/config.go

Whenever a package is added to `local_packages`, the properties `Language`, `Runtime` and `Description` are removed. Making `ops pkg list --local` not displaying those information even though having columns dedicated for them.
This PR fixes this issue by keeping the related properties.

Allow `Language`, `Runtime` and `Description` properties in manifest configuration

---

cmd/download_package.go

Related to #1070.
The code used `err == nil`, not that much of a best practice 🙃. It's cleaner that way.

Refactorize `extractFilePackage`

---

cmd/cmd_pkg.go
cmd/download_package.go
cmd/flags_pkg.go
lepton/const.go
lepton/image.go
lepton/package.go
types/config.go

Added support to override `PackageBaseURL` and `PackageManifestURL`. The override locations based on priority in order are `$HOME/.opsrc` then environment variable `OPS_PACKAGE_BASE_URL` and `OPS_PACKAGE_MANIFEST_URL` .... meaning environment variable will override `.opsrc`.
Added also support for local folder using `file://` prefix, e.g. if we have repo directory in local filesystem and we want to use it, we can override it like this
```
{
"PackageBaseURL": "file:///home/arknable/Development/Project/nanovms/example/package_repo",
"PackageManifestURL": "file:///home/arknable/Development/Project/nanovms/example/package_repo/manifest.json"
}
```
or using environment variables with above values.

Override PackageBaseURL and PackageManifestURL

---

cmd/cmd_pkg.go
lepton/package.go

Some module specify program location inside `sysroot`, hence we need to check it first and append the required `sysroot` folder.

Fix executable path construction to support binary inside sysroot

---

cmd/cmd_pkg.go
lepton/const.go
lepton/package.go

`OPS_HOME` value should be the parent directory in which `.ops` directory located, hence the home directory will be `$OPS_HOME/.ops`. if `$OPS_HOME/.ops` not exists, it will be created automatically.

Added option to override home path via OPS_HOME environment variable

---

lepton/image.go

While building an image and adding package files to it, if there is a
problem with a file such as a broken symlink, the addFile walk aborts
but the error is not handled. This has been changed so the err is logged
as an error and printed to the user but the image build continues since
missing package files aren't always required for the app to run. This fixes
some ops pkg load regressions such as in the python2.7 package.

Log missing files during image build instead of returning error

---

fs/manifest.go
lepton/image.go

- For a directory, use newly-added `MkdirPath()` instead of `AddDirectory()` of manifest.
- Handle symlink using `AddLink()` of manifest.

1086 Fix directory mapping

---

README.md

The `hi.js` example is quite outdated considering recent (not so recent) JavaScript best practices.

Modernize JavaScript example

---

fs/tfs.go

This allows specifying a "ManifestPassthrough" option with non-string attribute values, which may be necessary to configure kernel libraries such as cloud_init.
Example:
```
"ManifestPassthrough": {
"cloud_init": {
"download": [
{"src": "https://example1.com/README.md", "dest": "1.md"},
{"src": "https://example2.com/README.md", "dest": "2.md"}
]
}
}
```

fs/tfs.encodeMetadata(): add support for slices of arbitray data

---

cmd/cmd_pkg.go

Actual description for `ops pkg add`, "push a folder or a zipped package to the local cache", wasn't right as we don't allow zipped package.
This PR fixes the description to a better one.

Update `ops pkg add`'s description

---

cmd/flags_run_local_instance.go

The debug flag implements checks for a valid, statically linked executable
with debug symbols and aborts the command if failed. This prevents using
the debug flag with packages or arbitrary executables where you want to
debug nanos. This change prints out the failed checks as an error message
but does not abort the command.

Make debug flag executable checks non-fatal

---

cmd/cmd_deploy.go
cmd/cmd_run.go

Use filepath.Abs to create ProgramPath which automatically handles relative
or absolute paths instead of joining path elements manually.

Handle relative or absolute program paths

---

cmd/cmd_env.go
cmd/cmd_root.go
crossbuild/crossbuild.go
crossbuild/env.go
crossbuild/env_command.go
fs/manifest.go
go.mod
go.sum
lepton/image.go
lepton/ldd_darwin.go
lepton/ldd_linux.go
qemu/qemu_components.go
qemu/qemu_unix.go
types/config.go

This PR adds the 'env' set of commands, which allows to build an application in a Linux virtual machine and create a Nanos image from a set of files retrieved from the Linux virtual machine.
Usage summary for the new commands:
- `ops env install`: downloads a VM image from an online repository and extracts it in $OPS_HOME/crossbuild/images
- `ops env uninstall`: removes the VM image from $OPS_HOME/crossbuild/images
- `ops env build <build_file> --create-image -c config.json`: starts the build VM, connects to it via ssh, executes in sequence the set of commands specified in <build_file> (aborting the process if any of those commands returns an error), then reads any "Files", "Dirs" and "MapDirs" directives in config.json (which is a standard ops configuration file), copies the relevant …

Commands: add support for cross-build environment

---

fs/manifest.go

When using the TargetRoot option where libraries must be added to the image,
the entire host path was used in the image. This change removes the TargetRoot
path from the host library path to create the correct path for the image.

Remove target root prefix path from library path

---

cmd/cmd_image.go
fs/manifest.go
fs/reader.go
fs/tfs.go

The TFS filesystem driver now supports reading a filesystem from an image file. Three new subcommands for the `ops image` command have been added to exploit the new functionality. This makes ops implement most of the features of the `dump` tool.
Closes #911.

image command: add `cp`, `ls` and `tree` subcommands

---

aws/aws_volume.go
azure/azure_volume.go
cmd/cmd_volume.go
digitalocean/digital_ocean_volume.go
gcp/gcp_volume.go
hyperv/hyperv.go
lepton/provider.go
lepton/volume.go
oci/oci_volume.go
onprem/onprem_volume.go
onprem/onprem_volume_test.go
openstack/openstack_volume.go
upcloud/upcloud_volume.go
vbox/vbox_volume.go
vsphere/vsphere_volume.go
vultr/vultr_volume.go

The AWS volume create implementation first uploads to S3 a locally created volume, then creates a snapshot from the uploaded file, and finally creates a volume from the shapshot. When a volume is created from a snapshot, it is possible to specify a size parameter (which must be larger than or equal to the size of the snapshot): this allows to create arbitrarily sized volumes from small snapshots.
This commit changes the AWS volume create implementation so that the volume file being uploaded to S3 is created with the minimum size needed for the filesystem, and any volume size specified by the user is passed to the AWS volume creation API command.

AWS volume create: avoid uploading large files to S3 

---

fs/manifest.go
lepton/image.go
lepton/ldd_darwin.go
lepton/ldd_linux.go
lepton/ldd_windows.go

The getSharedLibs list generated by the Mac was not including the dynamic
loader so a dynamically-linked executable could not even start. The loader
location in the target root distribution is actually a symlink with an absolute
path, which revealed another problem in that absolute symlinks for libraries
were getting placed in the image at the location of the link target rather than
at the location of the symlink. This necessitated changing getSharedLibs to
return a map of string pairs so that the image path could be different
from the host file location. This also lets us remove AddLibrary since the
image path and host path no longer need to be calculated from a single string.

Fix Mac dependency generation for dynamic executables

---

vultr/vultr_instance.go

As the `SUBID` is needed to delete the instance, and instances created with `ops` don't have a name, I added it to the list table.
Before:
```
» ops instance list -t vultr
+------+--------+---------------------+-------------+---------------+
| NAME | STATUS |       CREATED       | PRIVATE IPS |  PUBLIC IPS   |
+------+--------+---------------------+-------------+---------------+
|      | active | 2021-11-14 23:02:07 |             | 207.246.84.57 |
+------+--------+---------------------+-------------+---------------+
```
After:
```
» ~/ops instance list -t vultr
+----------+------+--------+---------------------+-------------+---------------+
|  SUBID   | NAME | STATUS |       CREATED       | PRIVATE IPS |  PUBLIC IPS   |
+----------+------+--------+---------------------+-------------+------ …
```

Vultr: add SUBID to ListInstances

---

digitalocean/digital_ocean_store.go

Fix for https://github.com/nanovms/ops/issues/1037
```
» ~/ops image create -i spring-boot-hello --package java_1.8.0_191 -c config.json -t do
100% |████████████████████████████████████████|  [0s:0s]
BucketName is required
```
After defined the bucket name in the config:
```
» ~/ops image create -i spring-boot-hello --package java_1.8.0_191 -c config.json -t do
100% |████████████████████████████████████████|  [0s:0s]
bucket nanowg2 does not exist
```

DO: check if bucket exists when creating image

---

vultr/vultr_instance.go

Since the API response isn't very helpful:
Before:
```
» ~/ops instance create dceda686-9f2c-4b49-8e9d-f82b9ca36712 -t vultr
{"error":"Bad request.","status":400}
```
After:
```
» ~/ops instance create dceda686-9f2c-4b49-8e9d-f82b9ca36712 -t vultr
zone is required (-z)
```

Vultr: error if no zone is set

---

aws/aws_network.go

When an AWS subnet is created, it is tied to a specific availability zone, and this determines the zone of any instances that are subsequently created using this subnet.
This change adds the user-provided availability zone to the set of parameters used when creating a subnet, so that instances created by Ops are deployed in the expected availability zone.
Note: if no new subnet is created when creating an instance (such as when a default subnet already exists and the user doesn't specify a VPC and subnet in the cloud config), instances are still deployed in the availability zone of the existing subnet, which might be different from the zone specified in the cloud config.

AWS subnet: add availability zone from cloud config

---

cmd/cmd_pkg.go
lepton/image.go

This error does not give developer any useful information, and it is unnecessary panic.
`ops pkg list
`
failed getting packages: resource not found
panic: failed getting packages: resource not found
goroutine 1 [running]:
github.com/nanovms/ops/log.Panicf({0x24088fc, 0x1b}, {0xc0007bfc88, 0x1, 0x1})
/home/divar/Tutorial/Unikernel/nanovm/ops/log/logger_default.go:91 +0x108
github.com/nanovms/ops/cmd.cmdListPackages(0xc0004e7080, {0x3a42160, 0x0, 0x0})
/home/divar/Tutorial/Unikernel/nanovm/ops/cmd/cmd_pkg.go:108 +0xa9
github.com/spf13/cobra.(*Command).execute(0xc0004e7080, {0x3a42160, 0x0, 0x0})
/home/divar/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc00022f340)
/home/divar/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 …

improve dev ux of error and change panic log to error log

---

cmd/flags_run_local_instance.go
cmd/flags_run_local_instance_test.go

With the '-m' (or '--memory') command line flag, the 'ops run' command assigns the specified amount of RAM to the local instance being run. The flag value uses the same syntax as the "RunConfig.Memory" attribute in the configuration file (e.g. "64M", or "4G"), and if present overrides the value in the configuration file.

run command: add option to specify RAM size

---

README.md
lepton/ldd_darwin.go

In 2012, with the release of OS X 10.8 Mountain Lion, the name of the
system was shortened from Mac OS X to OS X. In 2016, with the release
of macOS 10.12 Sierra, the name was changed from OS X to macOS to
streamline it with the branding of Apple's other primary operating
systems: iOS, watchOS, and tvOS.
Reference: https://en.wikipedia.org/wiki/MacOS

Apple rebrands "OS X" as "macOS"

---

Makefile

Currently running the `make run` commands fails with this error
```
make run
go build -o ops -v ./...
go build: cannot write multiple packages to non-directory ops
```
This PR fixes it. Verified the build binary works correctly.

fix 'make run' command failing

---

cmd/flags_build_image.go
lepton/image.go
types/config.go

This PR adds the `--disable-args-copy` option. I didn't want the first argument to be automatically copied as I was manually copying files and directory using a config file. This might be useful for other people.

Add an option to disable automatic args file copy

---

lepton/image.go

add ops run should state a release is not found if it doesn't

---

cmd/cmd_pkg.go
install.sh
lepton/const.go
lepton/login.go

Adds the `ops pkg login <apikey>` command which validates the api key from packagehub and stores it in `~/.ops/credentials` to be used in other commands.
- Login to packagehub
- Generate an API key using the api key section
- use that api key in ops using `ops pkg login <key>`
- if the api key is correct you will see a message `Login Successful as user <Username>`.
- if the api key is incorrect you will see `incorrect api-key` error

add pkg login command and related functions

---

aws/aws_image.go
cmd/cmd_pkg.go
lepton/push.go

This PR implements the command `ops pkg push` which allows a user to push their custom local package to the packagehub repository.
- `ops pkg login` <- First login into packagehub
- Find the name of the local package you want to upload using `ops pkg list --local`. 
- run this command `ops pkg push <package-name>`
- `ops pkg login <api-key>`
- `ops pkg from-docker node:16.3.0 -f node`
- `ops pkg push node-16.3.0`

Implement ops pkg push 

---

lepton/image.go

This can be used by Nanos to identify the image where it is running (see e.g. https://github.com/nanovms/nanos/pull/1674).

Image create: add IMAGE_NAME environment variable

---

aws/aws.go
aws/aws_image.go

putsnapshot to EBS handler

---

aws/aws_instance.go
lepton/image.go
types/config.go

This PR has some miscellaneous changes. It adds a new Config option, KlibDir, to specify the location of Klibs when using
a custom kernel. It also filters out Terminated instances when looking up an instance on AWS so operations can be
applied to the correct (non-terminated) instance of the same name.

Add KlibDir and filter out Terminated AWS instances

---

aws/aws_instance.go
types/config.go

With this change, when creating an AWS instance it is possible to specify in the configuration file an elastic IP address to be
associated to the instance. Example:
```
"CloudConfig" :{
"ElasticIP": "1.2.3.4"
}
```
The IP address must be allocated to the AWS account from which the instance is being created.

AWS: add support for associating elastic IP address to instance

---

lepton/login.go
lepton/package.go

This is how it would look like post this PR change
```
+---------------+-------------+----------------+----------+---------+-------------+
|   NAMESPACE   | PACKAGENAME |    VERSION     | LANGUAGE | RUNTIME | DESCRIPTION |
+---------------+-------------+----------------+----------+---------+-------------+
| g-nanos | b2b         | b2b            |          |         |             |
+---------------+-------------+----------------+----------+---------+-------------+
| g-nanos | node        | node-16.3.0    | c        | c       | hi          |
+---------------+-------------+----------------+----------+---------+-------------+
```
You can see that once i added the runtime, language and description in the package.manifest they are picked up for `node-16.3.0`

fix local package listing

---

cmd/flags_nanos_version.go
cmd/flags_nightly.go

Since commit 8f40b6a61985dee97c2006b747fbc5227819cf01, specifying a custom kernel or boot file in config.json no longer works, because these file paths are overwritten with the paths from the current Nanos release.
This commit fixes the above issue so that file paths specified in config.json are only overwritten if a Nanos version (or a nightly build) is specified by the user.

Kernel and boot files: fix usage of custom files

---

aws/aws_volume.go
azure/azure_volume.go
cmd/cmd_volume.go
cmd/flags_build_image.go
cmd/flags_config.go
cmd/run_local_instance.go
digitalocean/digital_ocean_volume.go
gcp/gcp_volume.go
hyperv/hyperv.go
lepton/provider.go
lepton/volume.go
oci/oci_volume.go
onprem/onprem_instance.go
onprem/onprem_volume.go
onprem/onprem_volume_test.go
openstack/openstack_volume.go
proxmox/proxmox_volume.go
upcloud/upcloud_volume.go
upcloud/upcloud_volume_test.go
vbox/vbox_volume.go
vsphere/vsphere_volume.go
vultr/vultr_volume.go

This PR adds to the `volume attach` command the option to specify a volume identifier argument with format `%<attach_id>:<volume_name>` (where <attach_id> is an integer number indicating an attachment point) instead of `<volume_name>`.
Example: `ops volume attach myInstance %1:myVolume` attaches the volume identified by `myVolume` to an instance using 1 as attachment point.
The allowed values for the attachment point vary based on the deployment target; currently, this feature is only implemented for the AWS cloud provider, where the valid range for attachment points is [1-25].
If the attachment point is not specified in a volume attach command, a suitable attachment point is chosen automatically.
The attachment point can be used (alternatively to the volume name) to identify a volume in …

Volume attach: add support for specifying attachment point

---

azure/azure_volume.go
gcp/gcp_volume.go

In GCP, the attachment point is reflected in the device name associated to a disk (using the same format "persistent-disk-n" as used when a device name is assigned a default value).
In Azure, the attachment point is reflected in the disk Logical Unit Number.

GCP/Azure volume attach: implement handling of attachment point

---

aws/aws_image.go

Fixes leftover volumes after instance delete

AWS: Set DeleteOnTermination for boot disk when creating AMI

---

cmd/flags_build_image_test.go
onprem/onprem_volume_test.go

Fix TestBuildImageFlagsMergeToConfig by adding the UefiBoot path to expected results and fix miscellaneous symlink
error in TestBuildImageFlagsMergeToConfig by removing created symlink between tests.
For flags merging, the UefiBoot path is set in updateNanosToolsPaths() even if Uefi is not set.

Fix CI errors

---

azure/azure.go
azure/azure_image.go
azure/azure_instance.go
azure/azure_store.go
azure/azure_volume.go
go.mod
go.sum

This change configures the OsDisk to be removed automatically when the instance
is deleted in Azure. The compute module had to be upgraded to a newer version to
get access to the delete option, so other minor api changes related to the upgrade
had to be made.

Azure: Remove os disk on instance delete

---

cmd/cmd_pkg.go
lepton/package.go

currently when you create a package locally using `from-docker` or manually and try to upload it to `repo.ops.city` then ops throws error `no local package with the name <name> found` even if the package is present locally.
This PR fixes the above bug.

fix 'no local package of name found' error when pushing local packages

---

cmd/cmd_pkg.go
lepton/package.go
lepton/push.go

This change adds the support for uploading to org namespace. The way it works is that now you can provide an optional namespace prefix to your local folder
```
ops pkg push test/golang-1.8.1
```
Here ops will use the `test` as namespace and `golang-1.8.1` would be folder name it will search in `local_package`.

Add feature to upload public and private packages to organization namespaces

---

cmd/cmd_pkg.go
lepton/package.go

Fixes the version mismatch when `v` is set as prefix.
`node_v16.5.0` folder but manifest says `16.5.0`. So now we fuzzy match the version.
Also only read local manifest if it exists

fuzzy match version when pushing package and some fixes

---

fs/manifest.go
lepton/volume.go

The mount path for a volume may now optionally have ":ro" appended to it
indicating to mount read-only. AddMount must be changed to handle trimming
this from the path in order to create a correct mount directory, and AddMounts
changed to save the flag back to the mount path after removing it.

Handle read-only flag appended to mount paths

---

README.md

For at least a couple changes, I edited them based on my intuition of what was meant.
Please check the following before adopting this into the master branch:
Line 172: "tkt" == "ticket"
Line 180: "security at" == "security[at]nanovms[dot]com"

Updating README.md to be clearer for new readers.

---

.circleci/config.yml
gcp/gcp_image.go

GCP t2a instances boot with UEFI and thus require an UEFI bootloader in their images. This commit enables automatically UEFI when an image is being created for a GPC t2a instance.
The XCode version used in the CircleCI Mac build is being updated to the latest supported version 14.0.0, since the previously used version 12.2.0 is no longer supported by CircleCI.

GCP images: automatically enable UEFI on ARM images

---

proxmox/proxmox.go
proxmox/proxmox_image.go
proxmox/proxmox_instance.go

Added a new environment variable NODE_NAME for use with ProxMox.
If NODE_NAME is not set, then NODE_NAME = "pve" as auto fallback with use "pve" value for backward compatibility.

Adding ProxMox NODE_NAME configurable environment variable

---

proxmox/proxmox.go
proxmox/proxmox_checks.go
proxmox/proxmox_image.go
proxmox/proxmox_instance.go

Added functions with checks {"data": null} or {"data":[]} results from ProxMox API.
This is need for checking permissions in proxmox, correctness environment variables etc.
It is required in order to stop the ops giving the result as if everything is fine, but in fact nothing works with proxmox.
Currently in error messages uses 'local' and 'local-lvm' hard-coded words, later when we have customizable name of storages, this words be replaced by variables.

Add checks for data results from ProxMox API

---

proxmox/proxmox_checks.go
proxmox/proxmox_instance.go

Added capture errors from ProxMox API.
Unfortunately, ProxMox does not always return an error, for example, in the case of a disk move, if there is no storage local-lvm, then the error is not returned. ProxMox doesn't have the best API.

Added error checking coming from ProxMox API

---

proxmox/proxmox_instance.go
types/config.go

this is a simple pr to enable multiple nics talking to different/same bridges like so (dhcp only for now):
```
{
"RunConfig": {
"Nics": [
{
"BridgeName": "vmbr0"
},
{
"BridgeName": "vmbr0"
}
]
}
}
```
for now this only support proxmox, i'd imagine we'll end up deprecating the older RunConfig networking settings as we add this to more providers

adding in support for multiple nics in proxmox

---

lepton/helpers.go
proxmox/proxmox.go
proxmox/proxmox_image.go
proxmox/proxmox_instance.go

This pull request contains cosmetic changes, minor refactoring, capitalization of option names in the configuration file.
Removed unnecessary type conversions and checks. Everything is converted to a string type.
Example of config.json for Proxmox module (Current state):
```
{
"Dirs": ["etc"],
"NameServers": ["172.21.1.51"],
"ManifestPassthrough": {
"syslog": {
"server": "172.21.1.51"
}
},
"TargetConfig": {
"Arch": "x86_64",
"Machine": "q35",
"Sockets": "1",
"Cores": "8",
"Numa": "0",
"Memory": "4096M",
"BridgePrefix": "vmbr",
"IsoStorageName": "local",
"StorageName": "local-lvm",
"Protection": "0",
"Onboot": "1"
},
"RunConfig": {
"Klibs": ["syslog"],
"Accel": true,
"InstanceName": "usd",
"ImageName": "usd",
"Nics": [
{"IPAddress": "0.0.0.0", "NetMask": "255.255.255.0"},
{"IPAddress": …
```

Refactor ProxMox module, cosmetic fixes, better string logic

---

README.md
cmd/flags_config.go

This feature PR allows the JSON configuration file to interpolate environmental variables allowing templating for a multitude of reasons including but not limited to:
* staging versus production deployments
* secrets stored in the JSON file

[:tada:] add env var interpolation to config files

---

gcp/gcp_instance.go
types/config.go

This change adds 2 new attributes to the RunConfig JSON configuration object:
- GPUs (int): indicates how many GPUs should be attached to an instance (default: 0)
- GPUType (string): type of GPUs to be attached to an instance (cloud provider-specific)
Handling of these configuration option is implemented for the GCP cloud provider; example configuration suited for GCP:
```
"RunConfig": {
"GPUs": 1,
"GPUType": "nvidia-tesla-t4"
}
```

RunConfig: add support for GPUs

---

gcp/gcp_instance.go
gcp/gcp_instance_group.go
types/config.go

```json
{
...
"RunConfig": {
"CanIPForward": true
},
...
}
```

feat(gcp): manage ip forwarding on GCP instance creation

---

cmd/extract_from_docker.go

original shell script behaves differently in different shells (`bash`, `dash`, `zsh`, `ksh` - tested).
```sh
bash|dash|zsh|ksh extract_from_docker.sh ./keydb-6.3.1 | wc -l
```
| shell   |      old      |  new |
|----------|:-------------:|------:|
| bash  |  337 | 41 |
| dash  |    337   |41 |
| zsh     | 1512 |41 |
| ksh     |41 |41 |
---
**Note**: you can use the following command to compare versions
```
ops pkg from-docker eqalpha/keydb:x86_64_v6.3.1 -f keydb-server --verbose -n keydb-6.3.1
```

pkg(from-docker): extract fixes/optimization

---

cmd/extract_from_docker.go

clean paths otherwise copy to host fails, ex:
- **from** - `/usr/lib/jvm/java-11-openjdk-amd64/bin/../lib/jli/libjli.so`
- **to**      - `/usr/lib/jvm/java-11-openjdk-amd64/lib/jli/libjli.so`

pkg(from-docker): clean returned lib paths

---

gcp/gcp_instance.go

When executing the `ops instance create` command to create a GCP instance, if the CloudConfig.InstanceProfile configuration parameter is a non-empty string, the instance being created is associated to the service account identified by this string, with `cloud-platform` access scope. GCP service accounts are identified by an email address; the special string "default" indicates the default service account for a given project.
The service account specified in the configuration must exist in the GCP project when an instance is being created, otherwise an error is returned.
For more information about GCP service accounts, see https://cloud.google.com/compute/docs/access/service-accounts.

GCP: add support for associating a service account to an instance

---

lepton/ldd_darwin.go

If interpreter read from binary is absolute path, then `findLibs` does not locate the interpreter in `libDirs`.
This delta is fixing the issue by resolving the interpreter's base name.

Resolve interpreter's basepath before locating it

---

lepton/image.go
lepton/ldd_darwin.go
lepton/ldd_freebsd.go
lepton/ldd_linux.go
lepton/ldd_windows.go

Currently we support reading LD_LIBRARY_PATH from host and from ELF section. This PR adds third option to read from config to improve the command-line experience.
```sh
$ LD_LIBRARY_PATH=/tmp/linux/lib:/tmp/linux/usr/lib:/tmp/linux/lib/x86_64-linux-gnu:/tmp/linux/usr/lib/x86_64-linux-gnu \
ops run -c config.json publish/myApp
```
```sh
$ ops run -c config.json publish/myApp
```

Allow LD_LIBRARY_PATH read from config

---

types/config.go

Instead of getting all config items on manifest, we want just what is configured/set.
- **right now we have:**
```json
{
"Args": [
"node"
],
"DisableArgsCopy": false,
"BaseVolumeSz": "",
"Boot": "",
"UefiBoot": "",
"Uefi": false,
"BuildDir": "",
"CloudConfig": {
"BucketName": "",
"BucketNamespace": "",
"DomainName": "",
"StaticIP": "",
"EnableIPv6": false,
"Flavor": "",
"ImageType": "",
"ImageName": "",
"InstanceProfile": "",
"Platform": "",
"ProjectID": "",
"SecurityGroup": "",
"Subnet": "",
"Tags": null,
"VPC": "",
"Zone": ""
},
"TargetConfig": null,
"Debugflags": null,
"Dirs": null,
"Env": null,
"Files": null,
"Force": false,
"Kernel": "",
"KlibDir": "",
"MapDirs": null,
"Mounts": null,
"NameServers": null,
"NanosVersion": "",
"NightlyBuild": false,
"NoTrace": null, …
```

config(manifest): omit most of empty config items

---

digitalocean/digital_ocean_image.go
digitalocean/digital_ocean_instance.go

Hey, this is a continuation of https://github.com/nanovms/ops/pull/1240 that enabled the DO list instances and images commands to use the global `--json` flag.
I'm just playing around with ops, and needed json support for do commands, and it seemed easier to make a PR than make a ticket to ask for support for this in DO, hope that's ok.
~geoah

add global json flag support for listing do images and instances

---

cmd/cmd_pkg.go
cmd/cmd_run.go
provider/onprem/onprem_volume.go
qemu/qemu_unix.go
types/config.go

This change adds support for exporting host folders to the guest when running a local instance. Handling of the mount configuration options is being amended so that if there are no local volumes matching a label in a mount directive, a folder in the host filesystem is exported to the guest via VirtFS instead of using a pre-made volume.
This new functionality can be used in the 'run' and 'pkg load' commands, both as a command line option (e.g.
'--mounts host_dir:/guest_dir') and as a JSON attribute in the configuration file.

On premises instance: add support for VirtFS (9P filesystem)

---

provider/aws/aws_image.go

When creating a snapshot for an AWS image, the size of the snapshot volume is currently hardcoded to 1 GB; instead, it should reflect the actual size of the image being created, otherwise creation of images larger than 1 GB fails with error "Block index NNNN is beyond the volume size extent".

AWS createSnapshot(): fix setting of snapshot volume size

---

provider/vsphere/vsphere_instance.go

With the VMWare vSphere provider, if an `ops instance create` command is issued with an invalid image name, the CreateVM() function fails with an "Invalid configuration for device '1'" error message, from which it's difficult to infer the root cause of the problem. This change adds a call to Stat() on the datastore in order to check that the image file from which an the instance disk is being created exists, and report that the image name is invalid if the file is not found.
return appropriate error when image not found

vSphere instance create: check for existence of image

---

cmd/flags_nightly.go
cmd/flags_nightly_test.go
fs/mkfs.go
fs/mkfs_test.go
lepton/image.go
lepton/volume.go

With this change, if the `Boot` attribute in the configuration is empty, Ops does not require a boot.img file: if such file is found, it is inserted in the image being created, otherwise Ops builds internally a partition table when creating the image. This allows crating images without a legacy bootloader (e.g. images with a UEFI bootloader, or images with no bootloader at all, which can be used when the kernel binary file is passed directly to the hypervisor).
As part of these changes, if the user specifies in the configuration a kernel and/or boot file path, these settings are no longer overridden by the nightly flag.

Image creation: add support for images without a bootloader

---

provider/vultr/vultr_image.go
provider/vultr/vultr_instance.go

this copies the same layout as the Digitalocean provider. You previously discussed moving the JSON setting around.
Couldn't get this to build locally because the go mirror seems to be misbehaving around docker/distribution V2.8.0. Contemplated upgrading to v2.8.1 in the PR but maybe not.

add json options to vultr

---

provider/proxmox/proxmox_instance.go

This allows using the xterm.js console tool from the Proxmox web interface to see the output messages printed by an instance. xterm.js is a terminal emulator that captures the serial port logs output by an instance, and is not affected if the instance resets itself, thus allowing users to see e.g. crash messages if an instance reboot is triggered by a crash.
The alternative tool for seeing instance output via the Proxmox web interface is noVNC, which captures the logs sent to the VGA device; this tool is still available, and can be used independently from xterm.js.

Proxmox instance: add serial port device

---

qemu/qemu_unix.go

it was removed at https://github.com/nanovms/ops/pull/1489
If it was not intended, this pr restores it, otherwise ignore and close it.

log(qemu): restore qemu command verbose log

---

lepton/image.go

This picks up a dropped `err` variable in the `lepton` package.

lepton: fix dropped error

---

fs/tfs.go

This fixes a dropped `err` variable in the `fs` package.

fs: fix dropped error

---

qemu/qemu_unix.go

Some GPU devices (e.g. NVIDIA GeForce RTX 3090 and 4090) are VGA-compatible, thus their PCI subclass is 0x00; the existing Ops code is assuming that all GPUs have PCI subclass 0x02 (3D controller), which prevents setting up passthrough of VGA-compatible GPUs. This change removes the check for the PCI subclass when enumerating PCI devices, so that passthrough can be configured for all available GPUs.
In addition, the `rombar=0` option is being added to the Qemu command line, so that any PCI option ROM present in a GPU is not exposed to the VM; this fixes 2 problems:
- execution of the GPU ROM by the BIOS appears to lock up the VM (at least with Qemu version 6.2.0) when the GPU is the only VGA-compatible device in the VM
- configuration of a GPU in VGA text mode by the BIOS causes the VGA …

On-prem instances: add support for VGA-compatible GPUs

---

README.md

The README does have a link to https://ops.city/downloads but given the prevalence of MacOS as common development platform, it's handy to have the Homebrew install on the repos front page.

Added Homebrew install instructions to the README.md

---

provider/gcp/gcp.go
provider/gcp/gcp_image.go
provider/gcp/gcp_instance.go
provider/gcp/gcp_instance_group.go
types/config.go

I need a bit more control over what goes where.
The existing behavior is kept the same, unless one uses the new specific definitions.
- this config behaves the same as before:
```json
{
"CloudConfig": {
"Tags": [
{
"key": "instance-and-image",
"value": "instance-image"
}
]
}
}
```
- new config options - all options (you can set to `true` only what you need)
```json
{
"CloudConfig": {
"Tags": [
{
"key": "everywhere",
"value": "image-instance-metadata-valueAtnetwork",
"image_label": true, // added to image labels upon image build
"instance_label": true, // added to instance labels upon instance creation
"instance_metadata": true // added to instance custom metadata upon instance creation
"instance_network": true,  // tag VALUE is added to instance network tags
}
]
}
}
```

gcp(tags): backward compatible extended usage

---

cmd/cmd_pkg.go
cmd/extract_from_docker.go
cmd/flags_config.go

Made a few changes to `pkg` to address some things I came across while learning to use it recently.
- `pkg from-run` and `pkg from-pkg` were supposed to require the `-v` version flag to append to the package name, but the wrong variable was checked
- changed `pkg from-docker` to not append the version using a different format to `from-run` and `from-pkg`
- Made `pkg from-docker` copy over the Program using the executable's actual name instead of just "program". Loading a package by default saves an image using the name of its executable. This resulted in the image being shown with the name “program” under `ops image list`, which as someone new to OPS was very confusing and led me astray regarding an unrelated problem I was having. It also means the images from different local packages …

Minor pkg command changes

---

cmd/extract_from_docker.go
provider/onprem/onprem_volume.go

With this change, it is possible to specify a virtual ID in a mount directive for on-prem images, and then hot-plug a volume on a running instance by using the virtual ID in the `ops volume attach` command.
Example configuration:
```
"Mounts": {
"%1": "/data1",
"%2": "/data2"
},
"RunConfig": {
"QMP": true
}
```
After creating an image with `ops image create` and then an instance with `ops instance create`, a volume can be mounted in the "data1" directory with `ops volume attach myInstance %1:myVolume`, or in the "data2" directory with `ops volume attach myInstance %2:myVolume`.
It is still possible to not specify a virtual ID in the volume attach command, in which case the volume can only be mounted by using a mount directive that contains the volume identifier (UUID or label).

Onprem volumes: add support for virtual ID mounts

---

provider/gcp/gcp_instance.go
types/config.go

- `RunConfig.AttachVolumeOnInstanceCreate` - will attempt to attach already created disk(s)/volume(s) to the instance that is being created with `ops instance create --config config.json ....`
```json
{
"Mounts": {
"volume_name_or_id": "/db"
},
"RunConfig": {
"AttachVolumeOnInstanceCreate": true
}
}
```
**Note**: this feature is available on **ops config file only**

gcp(volumes): configurable autoattach upon instance creation

---

provider/gcp/gcp_image.go
provider/gcp/gcp_instance.go
types/config.go

This changeset adds a new boolean configuration option "ConfidentialVM" which, when set to true, will enable confidential computing on cloud providers that support this feature. It also adds support for this feature in Google Cloud Platform, where AMD-equipped instances can run with the Confidential VM service, which uses AMD Secure Encrypted Virtualization.

GCP: add confidential VM support (AMD SEV)

---

provider/gcp/gcp_instance.go
types/config.go

- **ThreadsPerCore**: The number of threads per physical core. To disable
simultaneous multithreading (SMT) set this to 1. If unset, the
maximum number of threads supported per core by the underlying
processor is assumed.
```json
{ 
"RunConfig": {
"ThreadsPerCore": 1
}
}
```

gcp(instance): manage simultaneous multithreading (SMT)

---

qemu/qemu_unix.go

The existing code is adding the `--no-reboot` flag to the Qemu command line when starting an on-prem instance; this flag was needed in the past when the Nanos kernel during shutdown was issuing a CPU reset via port 0x64 of the PS/2 controller, so that this reset would shut down the VM instead of resetting it. The current kernel no longer issues such CPU reset when running under Qemu: instead, it either performs an ACPI shutdown, or signals an exit code (when the `debug_exit` manifest option is present); thus, the `--no-reboot` flag is no longer needed.
The `--no-reboot` flag causes Qemu to shut down a VM (instead of resetting it) in response to the "system_reset" QMP command (which is executed when a reboot of an on-prem instance is requested); this change fixes the reboot functionality …

On-prem instances: fix reboot command

---

provider/aws/aws_image.go

This allows creating images to be run on AWS m7g and r7g instances. The list of Graviton-based instances is being removed since it is not needed to determine whether UEFI should be enabled (all ARM-based instances require a UEFI image).
In addition, UEFI enablement is being added when creating an image from a package.

AWS: add support for Graviton3 (ARM) instances

---

cmd/cmd_image.go
cmd/cmd_root.go
cmd/cmd_volume.go

- `ops volume ls`
```
list files and directories in volume
Usage:
ops volume ls <volume_name:volume_uuid> <path> [flags]
Flags:
-l, --long-format   use a long listing format
```
- `ops volume cp`
```
copy files from volume to local filesystem
Usage:
ops volume cp <volume_name:volume_uuid> <src>... <dest> [flags]
Flags:
-L, --dereference   always follow symbolic links in volume
-r, --recursive     copy directories recursively
```

feat(onprem): volume ls / volume cp - added

---

cmd/cmd_volume.go
fs/mkfs.go
fs/reader.go
fs/tfs.go

- `ops volume info`
```
get label/uuid of file system
Usage:
ops volume info <volume_file_path> [flags]
```
---
Examples:
- `ops volume info /tmp/snapshot-a1db-01.raw`
```sh
service-a1-db-v:b519fe87-0a33-500a-a33b-ee006bf6f4cb
```
- `ops volume info /tmp/snapshot-a1db-01.raw --json`
```json
{
"label": "service-a1-db-v",
"uuid": "b519fe87-0a33-500a-a33b-ee006bf6f4cb"
}
```
---
Useful mostly when exporting volumes from the cloud, and on the export flow naming gets lost/changed,  to mount locally for debug. There are other ways to archive the same, but require some more work.

onprem(volumes): ops volume info - get label/uuid from raw file

---

provider/digitalocean/digital_ocean_instance.go
provider/digitalocean/digital_ocean_network.go

Adding the `VPCUUID` field allows you to set a VPC of the droplet in the config.json. This way you can set VPC at instance creation without having to do a snapshot and then adding it to non-default VPC

Set VPC on instance creation using VPC name

---

lepton/package.go

Currently there is a bug where because the regexp is liberal enough to allow either _ or - to delimit the break between name and version, a package with dash will fail.
So for instance, a package like
my-package_1.2.3
Will have a name of "my" and a version of "package_1.2.3".
Not wanting to change this behaviour by simply changing the regex to only accept _ as a delimeter, I have changed the regex to split at the *last* match.
Fixes: https://github.com/nanovms/ops/issues/1594

Fix local package regexp for packages with hyphen in name

---

provider/onprem/onprem_volume.go

allow virtual identifiers when building images on one host for virt-fs but using them on a different host

fix for vfs mnt

---

cmd/cmd_pkg.go

Hey,
thanks for great project!
Based on issues that I had in #1604 , I thought it would be good add CPU Arch column so it's more obvious what are those packages. Also there are scenarios that you could have both images locally in different architectures and ability to differentiate them is important.
I also thought that behavior in list should be changed to show all arch by default, and to only filter them if someone adds `--arch`.
Let me know if this PR is acceptable and if would be acceptable to change pkg list behaviour.

feat: add CPU Architecture for Package Search & List

---

cmd/cmd_pkg.go
lepton/package.go
lepton/push.go

Basically this completes the loop for pushing packages with multiple arches via CLI.
Seeing as the current `--arch` flag accepts either `amd64` (as opposed to `x86_64`) or `arm64`, I'm manually changing this in the request data when it's pushed to the repo. 
Also falls back to `x86_64` if it's blank/unset
Also it slightly changes the behaviour when searching local packages, as previously it was erroring out if one of the existing arches didn't exist yet, so we just log it and continue instead.

use --arch for ops pkg push cmd (with sanitisation for amd64)

---

qemu/qemu_unix.go

related to https://github.com/nanovms/nanos/pull/2043

yanking highmem off for arch as we don't require it anymore

---

cmd/compose.go
qemu/qemu_unix.go

this allows users to mix/match arches for compose and defaults to normal/repo pkgs vs 'local' ones

Cross arch compose

---

cmd/compose.go
provider/onprem/instance.go
provider/onprem/onprem_instance.go

this also stores arch in the instance metadata for onprem

toggle metrics on by default for compose

---

cmd/cmd_run.go
cmd/run_local_instance.go
provider/onprem/onprem_instance.go
provider/onprem/onprem_volume.go
qemu/qemu_unix.go
qemu/qmp.go

this also moves some of the qmp handling

allow graceful shutdown on 'ops run' if qmp is passed

---

cmd/extract_from_docker.go

previously you had to explicitly state what you want so if the user doesn't provide it it falls back to whatever is in the last CMD layer (this could be extended by quite a bit in the future)

Allow cmd extraction from docker image layers

---

provider/gcp/gcp_image.go

The getArchitecture() function is being introduced to retrieve the architecture from the instance flavor.

GCP: add support for C4A (ARM-based Google Axion) instance types

---

provider/azure/azure_image.go

since gallery names are globally unique you need a diff. one for other regions.

allow overriding default azure gallery name

---

lepton/const.go
lepton/image.go
release.sh

klib dir was being set erroneously when not using nightly - this now sets it according to whatever kernel is being set

set proper klib dir for arm

---

fs/manifest.go
fs/mkfs.go
fs/reader.go
fs/tfs.go

- Update printable messages to use `%q` for quoting strings
- Replace generic error messages with specific formatted errors
- Ensure consistent error wrapping with `%w` across files

chore(fs): minor cleanup, easier to be imported

---

lepton/image.go
provider/azure/azure_image.go
provider/gcp/gcp_image.go
provider/gcp/gcp_volume.go

chore: lepton.CreateArchive can rename files
