nanovms/ops

lepton/config.go
lepton/package.go
ops.go

See issue https://github.com/nanovms/ops/issues/131.

Separate flags for nightly and updates.

---

lepton/qemu.go
lepton/qemu_test.go

Here params are configurable modulo knowing what the extra flag and config file attributes should look like.

Make params configurable

---

ops.go

Really simple filtering with a regex.
Let me get a test in there.

simple package list filtering.

---

Makefile
network.go
network_darwin.go
network_linux.go

Revert "remove the dhcp lookup; it's error prone and very slow"

---

lepton/qemu.go

I created this PR in order to handle exits. As for me it's useful to perform some kinds of cleanups or implementing #147

Handle exits

---

README.md

https://github.com/nanovms/ops/issues/197

Document minimum go version.

---

README.md

Links to basic usage examples.

Add basic usage examples.

---

README.md

Add `Installation` section with `source` and `binary` sub-sections.

Add binary/source installation instructions.

---

Makefile
config.json
lepton/config.go
lepton/gcp.go
lepton/gcpstore.go
lepton/onprem.go
lepton/provider.go
ops.go

ops deploy -c config.json [binary]
`export GOOGLE_APPLICATION_CREDENTIALS=prod-11097d3260d0.json`
config.json
```
{
"CloudConfig" :{
"ProjectID" :"",
"BucketName":""
},
"RunConfig" : {"Memory": "2G"}
}
```

Deploy to a gcp cloud bucket.

---

lepton/qemu.go

- Start() now uses Command() to configure cmd
- Stop() now waits for cmd (so if Hypervisor.Command() and Cmd.Start() was used we
wait for the completion properly)

Start() and Stop() fixes for nanos tests

---

cmd/load.go
cmd/package.go
cmd/utils.go

1. List contents of package
2. Show information about package

Add new package related commands

---

cmd/image.go
cmd/instance.go
cmd/package.go
lepton/config.go
lepton/gcp.go
lepton/onprem.go
lepton/provider.go

This patch provides way to list and delete images on GCP or onprem.

Add Image List/Delete and Instance List/Delete

---

lepton/qemu.go

add -cpu host for kvm

---

cmd/load.go

enable package developers to load local packages while developing, closes #342

add local flag

---

.circleci/config.yml
Makefile
cmd/build.go
cmd/load.go
cmd/manifest.go
cmd/network.go
cmd/root.go
cmd/root_test.go
cmd/run.go
cmd/update.go
cmd/utils.go
cmd/version.go
lepton/config.go
lepton/const.go
lepton/download.go
lepton/gcp.go
lepton/gcpstore.go
lepton/homedir.go
lepton/hv_support_darwin.go
lepton/hv_support_linux.go
lepton/hypervisor.go
lepton/image.go
lepton/ldd_darwin.go
lepton/manifest.go
lepton/onprem.go
lepton/package.go
lepton/provider.go
lepton/qemu.go
lepton/update.go

1. Add notification when newer version of nanos is available.
2. Update nanos with ops in ops update command.

Changes in Ops and Nanos update workflows

---

cmd/image.go
cmd/instance.go
cmd/utils.go
lepton/gcp.go
lepton/onprem.go
lepton/provider.go

[Fixes #363] Remove nanos prefix from image names 
Make argument in ops image delete positional 
[Fixes #356] Added flag to watch instance logs from the provider

Few fixes for Google Cloud Provider

---

cmd/image.go
cmd/utils.go
go.mod
go.sum
lepton/digital_ocean.go
lepton/objects.go
lepton/spaces.go
lepton/vultr.go

digital ocean has an oustanding issue that prevents automatic image creation via snapshot uploads cause they want a url with no query parameters on it (lame sauce), however, vultr is basically the same API and it works great

initial vultr && digital ocean support

---

lepton/manifest.go
lepton/manifest_test.go

do not merge until new nanos release

separating boot && root fs

---

cmd/utils.go

Resolves #405 by adding default config reader which will read from, in order of priority:
1. config file define using flags
2. config file location set on `OPS_DEFAULT_CONFIG`
3. config file location default on `~/.opsrc`
hence if all 1, 2, and 3 exist, `ops` will use value from 1.
Currently needs feedback on the following:
- config file is in `json` format, but if i see `~/.opsrc`, i would assume it is in env file format, which does not support array and map (current default config is expected to be valid `json` as well)
- have not set configuration via env var (either do it via 1 or set it explicity), not sure about priority of these values as well (i.e if value is set, is it overridden by config file/CLI flags?)
On approval, will update …

add default config parser

---

cmd/root_test.go
cmd/utils.go
lepton/image.go
lepton/manifest_test.go

use kernel.img for nightly

---

install.sh

fix install script appending config

---

cmd/build.go
cmd/image.go
cmd/instance.go
cmd/utils.go
lepton/vsphere.go
lepton/vsphere_test.go

add support for GOVC_USERNAME and GOVC_PASSWORD

---

cmd/image.go
cmd/instance.go
cmd/load.go
cmd/run.go
cmd/utils.go
install.sh
lepton/config.go
lepton/qemu.go
lepton/qemu_errors.go

This solves the issue https://github.com/nanovms/ops/issues/593

set accel by default

---

cmd/utils.go
lepton/manifest.go

448 - user should have better error msg when conflating dirs/files

---

install.sh

527 - ubuntu auto-install needs pkg name update

---

cmd/load.go

add flag manifest-name to ops load

---

lepton/image.go

fixing #613

---

lepton/qemu.go
lepton/qemu_errors.go

check for /dev/kvm user permissions instead of the check is a user in KVM group, try to activate HW accel anyway: -machine accel=kvm:tcg (#440)

check user have permissions for /dev/kvm

---

lepton/store.go

This gets rid of the `no such file or directory error` that is printed if the `volumes.json` file doesn't exist. If this filed doesn't exist this will print an empty list in the volumes list table.
This uses `errors.Is()` instead of comparing errors by the `==` operator as this recommended [here](https://golang.org/pkg/errors/#pkg-overview). 
Fixes #640

Return empty list if volumes config file not found

---

lepton/image.go
lepton/mkfs.go
lepton/mkfs_test.go
lepton/volume.go

* Creates structs that wraps all operations related with mkfs command like adding arguments and executing the command.

#609 extracts mkfs operations into it's own file

---

lepton/aws.go
lepton/config.go
lepton/qemu.go
lepton/qemu_test.go
lepton/update.go

I went through code and found few typographical errors. Comment if you need any more changes.

Fixing typographical error in project

---

lepton/aws.go

Added iterative method to add array of ports in security group.

Issue - #673

---

cmd/build.go
cmd/image.go
cmd/instance.go

Making "onprem" as default value to -t flag

Issue - #675

---

lepton/config.go
lepton/openstack.go

Able to create instance on Openstack. Right now it's working on default flavour "v2-highcpu-1". I am working on fetch flavour list and using one of them.
Also to create volume I added new variable in runconfig. Default value I kept it to 1GB.

Bugfix - #559

---

lepton/openstack.go

Added support to accept flavor from config file. In case flavor is not provided, first flavor from the list of flavour will be selected

Accept flavor from config file.

---

lepton/openstack.go

Openstack Instance name is unique for further instance activities. Added ID column instance list for.

Unique openstack instance name.

---

cmd/instance.go
lepton/aws.go
lepton/azure.go
lepton/digital_ocean.go
lepton/gcp.go
lepton/onprem.go
lepton/openstack.go
lepton/provider.go
lepton/vsphere.go
lepton/vultr.go

* Add safeguards to azure getIstances
* Add safeguard to openstack getInstances

Separate printing logs and getting logs concerns (closes #657)

---

lepton/openstack.go
lepton/openstack_volume.go

* Create, delete, list, attach and detach volumes

Add openstack volumes methods implementations #602

---

lepton/gcp.go
lepton/utils.go

Issue #705 
-Added support to expose list of ports given by user.
-Removed http and https ports as default ports.
-In case user doesn't provide flavour, added default flavour "g1-small"

Expose list of ports #705

---

cmd/instance.go
lepton/aws.go
lepton/openstack.go

Issue #625 
Removing default value for flavor flag
Added support for deleting openstack instance
Added default flavor for aws

Issue #625 - Removing default value for flavor flag

---

lepton/openstack_volume.go

Issue - #710 
Added support for soft rebooting openstack instance after attaching volume.

Issue - #710 - Soft reboot openstack instance.

---

lepton/gcp.go

* Assign tag to firewall rule and instance.

Create firewall rule that applies to launched instance (closes #705)

---

lepton/aws.go

Issue #721 
Added aws support for starting instance and stopping instance.

Issue #721 instance start/stop

---

cmd/instance.go
lepton/aws.go
lepton/config.go
lepton/gcp.go
lepton/provider.go
lepton/utils.go

#718
* Add domain name flag to create instance command.
* Automatically creates a managed zone and the A record for the instance launched.

Launches a GCP instance and regist a DNS record with its public IP

---

lepton/openstack.go
lepton/openstack_dns.go

Add openstack DNS operations

---

cmd/image.go
lepton/azure.go
lepton/azure_network.go
lepton/azure_storage.go

#724  - storage container exists
#723 - Instance unique name
#691 - delete image from bucket container
#690 - delete instance functionality
#581 - Unstub ports

Bugfix azure

---

lepton/digital_ocean.go
lepton/digital_ocean_test.go

Fixes #716 
* Fix the problem of printing raw bytes when listing images in Digital Ocean.
* Use Digital Ocean official SDK instead of calling the API directly.
This SDK parses the responses from Digital Ocean into structs, saving
the time wasted in parsing responses and errors from Digital Ocean
when there is a solution for it already.
* Print the list of images in a table.
* Add a unit test using [Go examples](https://golang.org/pkg/testing/#hdr-Examples) that ensures that the printed output to stdout is
correct. Ideally the printing logic should be separated from the listing of images, but that can be postponed for later.
Now listing Digital Ocean images prints as follows:
```bash
ahmedaabouzied@euclid:~/work/opensource/ops$ ./ops image list -t do …
```

Fix listing images on DO printing raw bytes

---

cmd/volume.go
lepton/aws_volume.go
lepton/azure_volume.go
lepton/digital_ocean_volume.go
lepton/gcp_volume.go
lepton/onprem_volume.go
lepton/openstack_volume.go
lepton/provider.go
lepton/volume.go
lepton/vsphere_volume.go
lepton/vultr_volume.go

* Add utility to print volumes list.
* Change gcp, onprem and openstack GetAllVolumes implementation
* Append status and created timestamp fields to nanos volumes data structure.

GetAllVolumes returns provider volumes. (closes #731)

---

lepton/aws.go
lepton/config.go

Allow defining an instance vpc and subnet in aws cloud provider

---

cmd/run.go
lepton/config.go
lepton/ldd_darwin.go
lepton/ldd_linux.go
lepton/qemu.go

* Disable accel;
* Append noaslr flag;
* Check program is statically linked and has debugging symbols.

Add flags to allow interactive debugging #715

---

go.mod
go.sum
lepton/aws.go
lepton/aws_volume.go

* Move logic to wait for snapshot completion to a dedicated function.
* Add function to create a new session using context variables.

#589 aws volume operations

---

lepton/homedir.go

Use current directory if there is no way of getting user home directory.

Allow ops usage inside an unikernel

---

lepton/gcp.go
lepton/gcp_volume.go

Reset instance after attaching or detaching a volume from a gcp instance

---

lepton/azure.go
lepton/azure_network.go

Allow specify vpc, subnet and security group on launching azure instances

---

lepton/azure.go
lepton/azure_network.go

* Erase error duplicated messages
* Fix network security group creation
* Remove concurrency code from deleting instance.

Allow set azure type on creating instance (closes #791)

---

lepton/image.go
lepton/manifest.go

#413
Prevent default files from overriding configuration files.

Add default files to manifest before using the configuration ones 

---

lepton/gcp.go
lepton/gcp_network.go

* Add methods to get and create networks and subnetworks.
* Move buildFirewalRules to gcp_network file
TODO: Set ip cidr range on create subnetworks method

Allow to set networks and subnetworks on gcp instances (closes #804)

---

cmd/image.go
lepton/azure_network.go
lepton/const.go
lepton/image.go
lepton/manifest.go

* Add utility to get klibs directory (nightly and latest version).

Include cloud_init klib on azure images (closes #797)

---

cmd/image.go

Auto-include tls and radar klibs if radar key is present in env

---

lepton/azure.go
lepton/azure_network.go
lepton/azure_network_test.go
lepton/logger.go
lepton/logger_test.go

(closes #793)
* Fix logger colors

Prevent the deleting of azure instance resources if used by other instances

---

cmd/image.go
cmd/utils.go
go.sum
lepton/aws_image.go
lepton/azure.go
lepton/azure_image.go
lepton/digital_ocean.go
lepton/digital_ocean_image.go
lepton/gcp_image.go
lepton/gcp_volume.go
lepton/onprem_image.go
lepton/onprem_volume_test.go
lepton/openstack_image.go
lepton/provider.go
lepton/vsphere_image.go
lepton/vultr_image.go

Remove unnecessary provider from context (closes #829)

---

lepton/qemu.go

fixes https://github.com/nanovms/ops/issues/839

always gen mac even for user-mode

---

cmd/image.go
lepton/image.go
lepton/manifest.go
lepton/manifest_test.go

Append radar klibs when adding environment radar variable in manifest

---

lepton/aws.go
lepton/config.go
lepton/onprem_volume_test.go
lepton/volume.go

In this pull-request, I am providing some updated changes to the configuration file. These suggestive changes are:
- Re-ordering the config variables in alphabetical order, which I am also working on for the "Configuration" page in the `ops-documentation`. This helps any developer/user who wants to use the OPS application by finding the necessary parameters.
- Adding comments to each variable to define what is used for, whether it is optional or not, and what the default value for the variable is. The comment structure is inspired by the config file for the Sarama library: https://github.com/Shopify/sarama/blob/master/config.go
@eyberg, any comments, feedback, or further suggestions for these changes?

(Suggestion): Config structure/order and variable descriptions

---

lepton/onprem_volume.go

show onprem volumes created at date

---

lepton/aws_image.go
lepton/aws_image_test.go

enable ena support on creating aws images (closes #575)

---

cmd/cmd_image.go
cmd/cmd_image_test.go
cmd/cmd_instance_test.go
cmd/cmd_load_test.go
cmd/cmd_run_test.go
cmd/flags_build_image.go
cmd/flags_build_image_test.go
cmd/flags_config_test.go
cmd/flags_pkg.go
cmd/flags_pkg_test.go
cmd/flags_test.go
cmd/utils_test.go

cmd refactor fixes

---

cmd/flags_start_image.go
cmd/flags_start_image_test.go
cmd/start_unikernel.go
config/config.go
network/setup_network_interfaces.go
network/setup_network_interfaces_test.go

* set default bridge name "br0" if bridged flag is specified and the bridgename it is not

support multiple bridges (closes 174)

---

aws/aws_instance.go
azure/azure_instance.go
cmd/cmd_deploy.go
digitalocean/digital_ocean_instance.go
gcp/gcp_instance.go
openstack/openstack_image.go
openstack/openstack_instance.go
upcloud/provider.go
upcloud/provider_instance.go
upcloud/provider_instance_test.go

enhance deploy command

---

hyperv/hyperv_api.go

Simplify Get-NetAdapter filter

---

qemu/hypervisor_unix.go
qemu/qemu_components.go
qemu/qemu_options_unix_amd64.go
qemu/qemu_options_unix_arm64.go
qemu/qemu_unix.go

initial rpi4 support

---

cmd/cmd_build.go
hyperv/provider_image.go
onprem/onprem_image.go

Show correct path of image built for hyper-v

---

cmd/cmd_build.go
cmd/cmd_deploy.go
cmd/cmd_image.go
cmd/cmd_run.go
cmd/cmd_update.go
cmd/cmd_volume.go
cmd/flags_nanos_version.go
cmd/flags_nightly.go
lepton/const.go
lepton/image.go

Allow to specify a old nanos version

---

cmd/cmd_image.go
cmd/cmd_instance.go
cmd/flags_build_image.go
onprem/instance.go
onprem/onprem_instance.go

create image requires program name

---

cmd/flags_pkg.go
cmd/flags_pkg_test.go

* configuration keys have precedence over package configuration

use flag trace in load command

---

README.md

* `ops load` -> `ops pkg load`
* fix annotations and markdown style in few places

Update examples in readme

---

cmd/cmd_volume.go
cmd/flags_build_image.go
cmd/flags_build_image_test.go
cmd/flags_config.go
cmd/flags_config_test.go
lepton/volume.go
onprem/onprem_volume.go
onprem/onprem_volume_test.go
types/config.go

fix volumes mounting from configuration

---

cmd/flags_build_image.go
cmd/flags_build_image_test.go

Prepend program name to args after merge

---

hyperv/provider_instance.go

Connect to the existing hyper-v virtual switch

---

cmd/cmd_volume.go
cmd/flags_run_local_instance_image.go
gcp/gcp_volume.go

set default netmask and gateway if ip address is specified

---

cmd/flags_run_local_instance_image.go
cmd/flags_run_local_instance_test.go
cmd/run_local_instance.go
lepton/image.go
network/setup_network_interfaces.go
types/config.go

https://github.com/nanovms/ops-documentation/issues/176#issuecomment-796609494

Rename IPAddr -> IPAddress

---

cmd/cmd_build.go
cmd/cmd_deploy.go
cmd/cmd_image.go
cmd/cmd_instance.go
cmd/cmd_pkg.go
cmd/cmd_run.go
cmd/cmd_volume.go
cmd/flags_config.go
lepton/config.go
types/config.go
upcloud/provider_test.go

(closes #959)
* Empty zone/projectID command flags were overriding configuration zone/projectID

fix zone and projectid handling on instance commands start, stop and logs

---

aws/aws_volume.go
azure/azure_volume.go
gcp/gcp_volume.go
onprem/onprem_volume.go
onprem/onprem_volume_test.go
openstack/openstack_volume.go
upcloud/provider_volume.go

closes #962 
* remove artifacts after uploading volume
* hides symlinks from volumes list

fix volumes list display

---

cmd/cmd_image.go
cmd/flags_config.go
cmd/flags_pkg.go
lepton/image.go

prevent configuration file from overriding program

---

aws/aws_image.go
aws/aws_instance.go
aws/aws_volume.go

* Use names in instances, images and volume operations instead of ids in AWS operations
* Filter volumes list by the ones that have the ops created by tag

Use resources names on aws operations (closes #384)

---

cmd/cmd_image.go
cmd/flags_provider.go
cmd/provider.go
go.mod
go.sum
hyperv/hyperv.go
hyperv/hyperv_instance.go
hyperv/powershell.go
oci/oci_image.go
vbox/vbox.go
vbox/vbox_image.go
vbox/vbox_instance.go
vbox/vbox_volume.go
wsl/wsl.go

closes #888 
Adds virtual provider with support to manage images and instances.
```
$ ops image list -t vbox
$ ops image create <elf file> -t vbox
$ ops image delete <image name> -t vbox
$ ops instance list -t vbox
$ ops instance create <image name> -p <port> -t vbox
$ ops instance start <instance name> -t vbox
$ ops instance stop <instance name> -t vbox
$ ops instance delete <instance name> -t vbox
```

add vbox integration

---

vbox/vbox_image.go
vbox/vbox_instance.go

de-register image from virtualbox on deleting image

---

aws/aws_instance.go
aws/aws_network.go

support ids and names of aws vpc/subnet/sg in configuration

---

aws/aws_instance.go
aws/aws_network.go
cmd/cmd_instance.go
onprem/onprem_instance.go

* fix bug that prevent creating instances on cloud providers that aren't onprem

add debug messages on aws instance creation

---

cmd/flags_config.go
cmd/flags_config_test.go

Fail running ops if configuration file have unknown fields

---

aws/aws_network.go

* Creates an internet gateway attached to the new VPC.
* Add routes to allow public access to VPC (ipv4 and ipv6)

Add routes to public access on a recently created VPC (closes #1018)

---

cmd/flags_config.go
cmd/flags_config_test.go
fs/manifest.go
lepton/config.go
lepton/image.go
types/config.go

fix paths specified in configuration file

---

aws/aws_image.go

* create snapshot with local file in aws (closes #974)

Speed up aws image creation

---

aws/aws.go
aws/aws_instance.go
azure/azure_instance.go
digitalocean/digital_ocean_instance.go
gcp/gcp_instance.go
hyperv/hyperv_instance.go
lepton/provider.go
oci/oci_instance.go
oci/oci_instance_test.go
onprem/onprem_instance.go
openstack/openstack_instance.go
upcloud/upcloud.go
upcloud/upcloud_instance.go
upcloud/upcloud_volume.go
vbox/vbox_instance.go
vsphere/vsphere_instance.go
vultr/vultr_instance.go

1. Added missing `GetInstance` method to some providers
2. Renamed existing `GetInstanceByID` methods as `GetInstance`

Added missing GetInstance to providers

---

cmd/cmd_pkg.go
lepton/const.go

Replaced `downloadLocalPackage` usage to `downloadPackage`

pkg get should download to packages directory

---

bash_completion.sh
install.sh

Added bash autocomplete script for ops commands

Added bash completion script

---

lepton/store.go
lepton/volume.go
vsphere/vsphere_instance.go
vsphere/vsphere_volume.go

* Power on a vsphere instance after creating it.
TODO:
* Deleting vsphere volume
* Using vsphere object manager on volume operations

Add vsphere volume operations (#586)

---

log/console_colors.go
log/logger.go
log/logger_test.go

Skip error flag check so error messages always displayed

Always display error messages

---

lepton/homedir.go

Optimize `HomeDir()`

---

gcp/gcp_instance.go

Any firewall rules being created as part of an instance creation should be deleted when the instance is deleted, otherwise if a user creates another instance specifying an instance name (with the `-i` command line option) equal to the name of a previously created (and then deleted) instance, creation of the second instance fails with `googleapi: Error 409: The resource 'projects/prod-xxxx/global/firewalls/ops-tcp-rule-myimage-myinstance' already exists, alreadyExists
Failed to add Firewall rule` (the instance itself is actually created, but any applicable firewall rules are not created).

GCP instance delete: remove firewall rules

---

cmd/cmd_image.go
onprem/onprem.go

For cloud-based image, check instance's image against image name instead of path.

Other than onprem, instance's image is not a path

---

cmd/cmd_pkg.go

It's actually not possible to get local packages' content.

Add `--local` flag to `pkg contents` command

---

cmd/extract_from_docker.go

Skip statically linked program with pkg from-docker

---

README.md

with miscellaneous minor improvements.
It is mainly to avoid maintaining up-to-date list of languages.
Fixes #1106.

Update README pointing to examples repo

---

vultr/vultr.go
vultr/vultr_image.go
vultr/vultr_instance.go

Doesn't make a much of a difference, but removes linting errors 🙂

Vultr: add missing error handling

---

digitalocean/digital_ocean_store.go

Fix https://github.com/nanovms/ops/issues/1166
Before:
```
» ops image create boringtun/target/release/boringtun -c config.json -t do
100% |████████████████████████████████████████|  [0s:0s]
POST https://api.digitalocean.com/v2/images: 400 {"id":"bad_request","message":"Your source URL is unreachable"}
{"image":{"created_at":"2021-11-14T21:45:05Z","description":"","distribution":"Unknown OS","error_message":"","id":95739054,"name":"boringtun.img","regions":[],"status":"NEW","tags":["createdBy:ops"],"type":"custom","updated_at":"2021-11-14T21:45:05Z"}}
```
After:
```
» ~/ops image create boringtun/target/release/boringtun -c config.json -t do                            1 ↵
100% |████████████████████████████████████████|  [0s:0s]
do image 'boringtun' created...
```

DO: fix bucket policy

---

digitalocean/digital_ocean_instance.go

Fix https://github.com/nanovms/ops/issues/1166#issuecomment-968370169
Instead of using a fake fingerprint, use all the keys present on the DO account.
Before:
```
» ops instance create boringtun.img -t do -z ams3
POST https://api.digitalocean.com/v2/droplets: 422 02:14:c3:d2:cd:4a:67:8b:43:b3:49:83:99:49:6a:58 are invalid key identifiers for Droplet creation.
```
After:
```
» ~/ops instance create boringtun.img -t do -z ams3
»
```

DO: create droplet with all keys by default

---

digitalocean/digital_ocean.go
vultr/vultr_image.go
vultr/vultr_instance.go

fix https://github.com/nanovms/ops/issues/1038

DO/Vultr: differentiate token env variable name

---

aws/aws_volume.go

Using a single hard-coded device name "/dev/sdf" for all volume attachments doesn't allow to attach more than one volume to a given instance: when trying to attach a second volume, the result is "InvalidParameterValue: Invalid value '/dev/sdf' for unixDevice. Attachment point /dev/sdf is already in use".
This change replaces the hard-coded device name with a name that is dynamically generated based on the existing block device mappings on a given instance. In addition, it removes the device name from the volume detach command, because there is no need to specify the attachment point if both the volume ID and the instance ID are specified.

AWS volumes: dynamically generate device name when attaching volume

---

qemu/qemu_unix.go

Closes https://github.com/nanovms/ops/issues/1210

disable hardware acceleration on darwin/arm64 arch

---

cmd/cmd_pkg.go
cmd/extract_from_docker.go

Closes https://github.com/nanovms/ops/issues/1116

implement copy flag for from-docker command

---

cmd/cmd_profile.go
lepton/const.go
lepton/ldd_freebsd.go
onprem/syswrap_freebsd.go
qemu/hv_support_freebsd.go
qemu/hypervisor_unix.go
qemu/qemu_options_unix_amd64.go
qemu/qemu_unix.go

this still relies on qemu for now but will run hello worlds

initial freebsd support

---

lepton/image.go

Allow directories in first argument copy

---

aws/aws_image.go
cmd/flags_global.go
types/config.go

add global flag json - json output current support for ops image list

---

aws/aws_instance.go
config.json
types/config.go

create IAM role when create instance

---

cmd/extract_from_docker.go

Closes https://github.com/nanovms/ops/issues/1254

use the correct version in manifest for docker packages

---

aws/aws_instance.go
aws/aws_instance_group.go
types/config.go

add auto scaling group when creating an instance

---

aws/aws_image.go

get architecture from flavor name

---

aws/aws_image.go

aws graviton instances set Uefi flag when BuildImage

---

aws/aws_image.go

add basic support for c6a instance types so ENA works

add support for the new c6a instance type

---

lepton/image.go

fixes https://github.com/nanovms/ops/issues/1280

fix the mac os build failing

---

cmd/flags_build_image.go
lepton/const.go
lepton/image.go

Potentially Closes https://github.com/nanovms/ops/issues/1262

[WIP] use a nanos version on klib directory

---

aws/aws_instance.go
gcp/gcp_network.go
types/config.go

closes https://github.com/nanovms/ops/issues/997

add support for static IP for GCP instance

---

gcp/gcp_instance.go

Closes https://github.com/nanovms/ops/issues/1109
Note - this will not help any existing instance and will only work for instances created after this PR is merged.

add image label to gcp instance on creation

---

aws/aws.go
aws/aws_image.go
aws/aws_instance.go
aws/aws_volume.go
aws/role.go
azure/azure.go
azure/azure_image.go
azure/azure_instance.go
azure/azure_network.go
azure/azure_store.go
digitalocean/digital_ocean_image.go
gcp/gcp_image.go
onprem/onprem_instance.go
openstack/openstack_image.go
vsphere/vsphere_image.go

fixing go-staticcheck warnings

 fix go-staticcheck warnings from the code

---

cmd/cmd_pkg.go
cmd/cmd_pkg_test.go
lepton/const.go
lepton/search.go

- Implements `ops pkg search [pkgName]` which searches package against repo.ops.city

add pkg search command to search packages against repo.ops.city

---

azure/azure_volume.go

This change fixes a bug where attaching a second volume accidentally removed
previously attached volumes because the disks array was being overwritten with
only the new disk.

Azure: Fix multiple volume attach

---

cmd/cmd_image.go

closes https://github.com/nanovms/ops/issues/1329

make zone flag optional for ops image mirror

---

cmd/cmd_instance.go
cmd/flags_create_instance.go
gcp/gcp_instance.go

closes https://github.com/nanovms/ops/issues/774

delete dns record when deleting gcp instance

---

UNIKERNELS.md

1. Adding a "?" to the end of the H1 since it is ultimately used as a question.
2. Hyphenating "single-process" when it is used as a modifier, but not when it could be interpreted as the subject.
3. Capitalizing proper nouns like "Ruby" and "Unix". 
4. ...and other minor details.

Fixing grammar/punctuation in UNIKERNELS.md

---

cmd/cmd_instance.go
go.mod
lepton/helpers.go
proxmox/proxmox.go
proxmox/proxmox_checks.go
proxmox/proxmox_image.go
proxmox/proxmox_instance.go
types/config.go

refactoring https://github.com/nanovms/ops/pull/1370 && adding in TargetConfig
merge https://github.com/nanovms/ops/pull/1372 first

Target cloud config

---

lepton/image.go
proxmox/proxmox_instance.go
qemu/qemu_components.go
qemu/qemu_unix.go

supports both static assignment and dhcp for proxmox
support for multiple local taps will come in diff pr

Multi nic support for proxmox

---

aws/aws_image.go
gcp/gcp_image.go
lepton/cloud.go

not sure if we should show these off/on by default but should definitely be available

show labels attached to images

---

cmd/cmd_instance.go
network/setup_network_interfaces.go
provider/onprem/onprem_instance.go

for some reason we only allowed this on ops run

allow bridge/tap on instance create for onprem provider

---

types/config.go

based on https://github.com/nanovms/ops-documentation/pull/411#issuecomment-1602193432

config: remove VirtfsShares from user file config

---

qemu/qemu_unix.go

This change adds support for running on-prem instances with GPU devices. These devices must be connected to the host (which must be an x86_64 Linux machine) and are made available to the guest via PCI passthrough.
To enable GPU passthrough on an on-prem instance, set the "GPUs" attribute of the "RunConfig" object in the Ops configuration to the number of GPUs to be made available to the instance. Example:
```
"RunConfig": {
"GPUs": 1
}
```
GPU passthrough requires I/O virtualization to be supported and enabled in the host: this may require enabling VT-d (for Intel CPUs) or AMD IOMMU (for AMD CPUs) in the BIOS settings, and adding the "intel_iommu=on iommu=pt" (for Intel CPUs) or "amd_iommu=on iommu=pt" (for AMD CPUs) options to the Linux kernel command line. In addition, the vfio-pci …

On-prem instances: add support for GPU passthrough

---

cmd/cmd_volume.go

```sh
ops volume tree --help
display volume filesystem contents in tree format
Usage:
ops volume tree <volume_name:volume_uuid> [flags]
```
```sh
$ ops volume tree test
/
|   003c4343abc9aa3cda64777c3d6dd7ad508727c5e26911d1ab37fe64dee6fdb6
|   |   LOG
|   |   000058.sst
|   |   000064.sst
|   |   OPTIONS-000069
|   |   LOG.old.1701954099064873
|   |   000066.log
|   |   MANIFEST-000067
|   |   OPTIONS-000063
|   |   CURRENT
|   |   000059.sst
|   |   LOCK
|   |   LOG.old.1701851204217980
|   |   IDENTITY
|   | 
```

feat(onprem): volume tree - added

---

provider/gcp/gcp_volume.go

Useful in some pipelines that could fail at times when the previous steps are not fully completed (from the cloud perspective)
1. ops volume delete vol-a
2. ops volume create vol-a
3. use vol-a

gcp(volumes): add some status poll upon create/delete

---

cmd/cmd_pkg.go
cmd/cmd_pkg_test.go
cmd/download_package.go
cmd/extract_from_docker.go
cmd/flags_pkg.go
cmd/flags_pkg_test.go
lepton/const.go
lepton/package.go

this will be a non-backwards compatible but necessary change

enable pkg w/same namespace/name/version but diff arch locally

---

cmd/cmd_pkg.go
cmd/flags_pkg.go
lepton/package.go
lepton/push.go
types/config.go

rip runtime from pkg

---

fs/manifest.go
lepton/image.go

not sure if this is the best place to add this and should make the error msgs super explicit before merging

do a quick arch check to ensure both chosen arch && user program matches

---

cmd/cmd_network.go

- Replace `brctl` commands with `ip` commands for bridge management
- Update error messages for clarity on command failures
- Use `ip link show` to check device existence
- Create bridge with `ip link add` command
- Set bridge device IP address using `ip addr add`
- Bring bridge device up with `ip link set dev up`
- Bring bridge device down using `ip link set dev down`
- Delete bridge device using `ip link delete` command
- Check empty bridge with `ip link show master` command

chore: network - use 'ip' instead of 'brctl' and 'ifconfig'

---

cmd/cmd_image.go
fs/reader.go

- `ops image ls   --bootfs ...` - list over boot filesystem
- `ops image tree --bootfs ...` - tree over boot filesystem
- `ops image cp   --bootfs ...` - copy from boot filesystem
- Implement `NewReaderBootFS` for boot filesystem (`kernel` + `klib`) handling

feat: support image (ls, tree, cp) over bootfs

---

cmd/download_package.go
cmd/extract_from_docker.go

fixes arch (and prob deb) when mving files across partitions from tmp
note: there is another fix for grabbing the correct loader in https://github.com/nanovms/ops/pull/1692

add support for rename across partitions

---

install.sh

minor fix: exit install script if qemu installation not found
